# Config
$conf = ~/.config/hypr/conf
$Cconf = ~/.config/hypr/conf/custom-desktop.conf

source = colors.conf
source = $conf/env.conf
source = $conf/execs.conf
source = $conf/decoration.conf
source = $conf/animations.conf
source = $conf/input.conf
source = $conf/general.conf
source = $conf/keybinds.conf

# Custom
source = $Cconf

# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
workspace = f[1], gapsout:0, gapsin:0
windowrule {
    name = no-gaps-f1
    match:float = false
    match:workspace = f[1]

    border_size = 0
    rounding = 0
}


# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}


##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = on
}


# TAKEN FROM HYDE 
# Add blur to wlogout
layerrule = blur true,match:namespace logout_dialog
layerrule = blur true,match:namespace rofi
layerrule = ignore_alpha 0,match:namespace rofi

# Float and center nwg-look
windowrule = float on, match:class nwg-look
windowrule = size (monitor_w*0.4) (monitor_h*0.6), match:class nwg-look
windowrule = center on, match:class nwg-look

# Pavu-control
windowrule = float on, match:class org\.pulseaudio\.pavucontrol|yad-icon-browser
windowrule = size (monitor_w*0.4) (monitor_h*0.6), match:class org\.pulseaudio\.pavucontrol|yad-icon-browser
windowrule = center on, match:class org\.pulseaudio\.pavucontrol|yad-icon-browser


# nmtui
windowrule = float on, match:class nmtui
windowrule = size (monitor_w*0.4) (monitor_h*0.6), match:class nmtui
windowrule = center on, match:class nmtui

windowrule = workspace special:communication, match:class discord|equibop|vesktop|whatsapp

# Opacity for windows
windowrule = opacity 0.9 override 0.85 override, match:fullscreen false

windowrule = opacity 0.90 override 0.90 override 1,match:class ^(brave-browser)$
