# Main monitor
monitor = DP-1, 2560x1440@359.98, 1920x0, 1, bitdepth, 10
# Secondary
monitor = DP-2, 1920x1080@144.00, 0x0, 1, bitdepth, 10, cm, auto


misc {
		vrr = 3
	}

render {
    cm_fs_passthrough = 1
}

quirks {
    prefer_hdr = 2
  }



# NVIDIA
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = ELECTRON_OZONE_PLATFORM_HINT,auto
