# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Polkit authentication agent (GUI privilege escalation) for example promptig for password when opening another drive
exec-once = systemctl --user start hyprpolkitagent

# Keyring 
 exec-once = gnome-keyring-daemon --start --components=secrets

#TMUX
exec-once = tmux new-session -d

# Waybar
exec-once = waybar

# Wallpaper daemon
exec-once = awww-daemon
