return {
  -- "nvim-tree/nvim-tree.lua",
  -- version = "*",
  -- lazy = false,
  -- dependencies = {
  --   "nvim-tree/nvim-web-devicons",
  -- },
  -- opts = {
  --   view = {
  --   width = 35,
  --   relativenumber = true,
  --   },
  --
  --   git = {
  --       ignore = false,
  --   },
  --
  --   renderer = {
  --       indent_markers = {
  --           enable = true,
  --       },
  --
  --       icons = {
  --           glyphs = {
  --               folder = {
  --                   arrow_closed = "", -- arrow when folder is closed
  --                   arrow_open = "", -- arrow when folder is open
  --               },
  --           },
  --       },
  --   },
  -- },
  --
  -- config = function(_, opts)
  --   require("nvim-tree").setup(opts)
  --
  --   -- set keymaps
  --
  --   vim.keymap.set("n", "<leader>ee", "<cmd>NvimTreeToggle<CR>", { desc = "Toggle file explorer" }) -- toggle file explorer 
  --   vim.keymap.set("n", "<leader>ef", "<cmd>NvimTreeFindFileToggle<CR>", { desc = "Toggle file explorer on current file" }) -- toggle file explorer on current file
  --   vim.keymap.set("n", "<leader>ec", "<cmd>NvimTreeCollapse<CR>", { desc = "Collapse file explorer" }) -- collapse file explorer
  --   vim.keymap.set("n", "<leader>er", "<cmd>NvimTreeRefresh<CR>", { desc = "Refresh file explorer" }) -- refresh file explorer
  --
  -- end
}
